name: XMLlint Action
on: push

jobs:
  xml-linters:
    name: XMLlint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Enable annotations
      uses: korelstar/xmllint-problem-matcher@v1
    - name: Lint XMLfiles using xmllint
      #uses: jonasbn/xmllint-action@17419913cd0a340cbf6b17d426e3bcd700d84855
      #uses: ChristophWurst/xmllint-action@v1
      uses: ./.github/actions/xmllint
      with:
        xml-file: ./xml/{,**/}*.xml
        xml-schema-file: ./epp.xsd
